// resources/js/Pages/Admin/Platforms/Index.vue
<template>
    <app-layout>
        <template #header>
            <h2 class="m-0">Platforms</h2>
            <div>
                <a :href="create_url" class="btn btn-light btn-sm"><i class="far fa-fw fa-plus me-1"></i> New</a>
            </div>
        </template>

        <div class="container my-3">
            <div class="row g-3">
                <card v-for="platform in platforms" :key="platform.id" :color="platform.color">
                    <template #title>
                        <i :class="'me-2 far fa-fw fa-' + platform.icon"></i>
                        {{ platform.name }}
                    </template>
                    <template #actions>
                        <a :href="platform.edit_url" class="btn btn-primary btn-sm">
                            <i class="far fa-pencil me-1"></i> Edit
                        </a>
                    </template>
                </card>
            </div>
        </div>
    </app-layout>
</template>

<script>
    import AppLayout from '@/Layouts/AppLayout'
    import Card from '@/Jetstream/Card'

    export default {
        components: {
            AppLayout,
            Card
        },

        props: {
            platforms: Array,
            create_url: String
        }
    }
</script>

// resources/js/Pages/Admin/Platforms/Index.jsx
import React from "react";

import NaviBar from "@/Components/NaviBar";
import PlatformIcon from "@/Components/Platforms/PlatformIcon";
import Status from "@/Components/Status";
import Admin from "@/Layouts/Admin";

import { Link } from "@inertiajs/react";
import Amicon, { aiPlus } from "@studio384/amaranth";

export default function Index({ can, platforms, status }) {
  return (
    <Admin>
      <NaviBar
        actions={
          can.platforms.create && (
            <Link href={route("admin.platforms.create")} className="btn btn-primary btn-sm">
              <Amicon icon={aiPlus} /> New
            </Link>
          )
        }
      >
        Platforms
      </NaviBar>

      <div className="container">
        <Status status={status} />
        <div className="row g-1">
          {platforms.map((platform) => {
            const platformStatus = [];

            platform.active && platformStatus.push("Active");
            platform.legacy && platformStatus.push("Legacy");

            return (
              <div className="col-xl-4 col-xxl-3 col-6" key={platform.id}>
                <Link href={route("admin.platforms.edit", platform)} className="card border-0 shadow-sm">
                  <div className="card-body">
                    <div className="d-flex flex-row">
                      <h3 className="h6 mb-0">
                        <PlatformIcon platform={platform} color />
                      </h3>
                      <div className="ms-2">
                        <h3 className="h6 mb-0">{platform.name}</h3>
                        <p className="text-muted mt-n1 mb-0">
                          <small>{platformStatus.join(", ")}</small>
                        </p>
                      </div>
                    </div>
                  </div>
                </Link>
              </div>
            );
          })}
        </div>
      </div>
    </Admin>
  );
}
