// resources/js/Pages/Auth/ForgotPassword.vue
<template>
    <jet-authentication-card>
        <div class="mb-4 text-sm text-gray-600">
            Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.
        </div>

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <jet-validation-errors class="mb-4" />

        <form @submit.prevent="submit">
            <div class="mt-4 form-floating">
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus />
                <jet-label for="email" value="Email" />
            </div>

            <div class="d-flex justify-content-between align-items-center mt-3">
                <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Email Password Reset Link
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import JetAuthenticationCard from '@/Jetstream/AuthenticationCard'
    import JetButton from '@/Jetstream/Button'
    import JetInput from '@/Jetstream/Input'
    import JetLabel from '@/Jetstream/Label'
    import JetValidationErrors from '@/Jetstream/ValidationErrors'

    export default {
        components: {
            JetAuthenticationCard,
            JetButton,
            JetInput,
            JetLabel,
            JetValidationErrors
        },

        props: {
            status: String
        },

        data() {
            return {
                form: this.$inertia.form({
                    email: ''
                })
            }
        },

        methods: {
            submit() {
                this.form.post(this.route('password.email'))
            }
        }
    }
</script>

// resources/js/Pages/Auth/ForgotPassword.jsx
import React, { useState } from 'react';
import { Inertia } from '@inertiajs/inertia';
import { InertiaHead } from '@inertiajs/inertia-react';

import Auth from '../../Layouts/Auth';

import AmaranthIcon, { aiPaperPlane } from '@changewindows/amaranth';

export default function ForgotPassword({ app, status }) {
    const [form, setForm] = useState({ email: '' });

    function handleSubmit(event) {
      event.preventDefault();
      Inertia.post('/forgot-password', form);
    }

    return (
        <Auth>
            <InertiaHead title="Forgot Password" />

            <form onSubmit={handleSubmit} className="row g-3">
                <div className="col-12">
                    <p className="text-muted"><small>Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.</small></p>
                </div>
                {Object.keys(status).length > 0 &&
                    <div className="col-12">
                        <div className="alert alert-danger mb-0">
                            {Object.keys(status).map((errorGroup, _key) => (
                                status[errorGroup].map((error, key) => (
                                    <span key={key}>{error}</span>
                                ))
                            ))}
                        </div>
                    </div>
                }
                <div className="col-12">
                    <div className="form-floating">
                        <input type="email" className="form-control" id="email" value={form.email} onChange={(event) => setForm({ email: event.target.value })} autoFocus />
                        <label htmlFor="email">Email</label>
                    </div>
                </div>
                <div className="col-12 d-flex justify-content-between">
                    <div className="flex-grow-1" />
                    <button className="btn btn-primary" type="submit">
                        <AmaranthIcon icon={aiPaperPlane} /> Send password reset link
                    </button>
                </div>
            </form>
        </Auth>
    )
}
