// resources/js/Pages/Auth/Login.vue
<template>
    <jet-authentication-card>
        <jet-validation-errors class="mb-4" />

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div class="form-floating">
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus />
                <jet-label for="email" value="Email" />
            </div>

            <div class="mt-4 form-floating">
                <jet-input id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="current-password" />
                <jet-label for="password" value="Password" />
            </div>

            <div class="mt-4">
                <div class="form-check">
                    <jet-checkbox name="remember" v-model="form.remember" />
                    <label class="form-check-label">Remember me</label>
                </div>
            </div>

            <div class="d-flex justify-content-between align-items-center mt-3">
                <inertia-link v-if="canResetPassword" :href="route('password.request')">
                    Forgot your password?
                </inertia-link>

                <jet-button :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Login
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import JetAuthenticationCard from '@/Jetstream/AuthenticationCard'
    import JetButton from '@/Jetstream/Button'
    import JetInput from '@/Jetstream/Input'
    import JetCheckbox from '@/Jetstream/Checkbox'
    import JetLabel from '@/Jetstream/Label'
    import JetValidationErrors from '@/Jetstream/ValidationErrors'

    export default {
        components: {
            JetAuthenticationCard,
            JetButton,
            JetInput,
            JetCheckbox,
            JetLabel,
            JetValidationErrors
        },

        props: {
            canResetPassword: Boolean,
            status: String
        },

        data() {
            return {
                form: this.$inertia.form({
                    email: '',
                    password: '',
                    remember: false
                })
            }
        },

        methods: {
            submit() {
                this.form
                    .transform(data => ({
                        ... data,
                        remember: this.form.remember ? 'on' : ''
                    }))
                    .post(this.route('login'), {
                        onFinish: () => this.form.reset('password'),
                    })
            }
        }
    }
</script>

// resources/js/Pages/Auth/Login.jsx
import React, { useState } from 'react';
import { Inertia } from '@inertiajs/inertia';
import { InertiaLink, InertiaHead } from '@inertiajs/inertia-react';

import Auth from '../../Layouts/Auth';

import AmaranthIcon, { aiArrowToBracket, aiShieldKey } from '@changewindows/amaranth';

export default function Login({ app, status }) {
    const [form, setForm] = useState({ email: '', password: '', remember: true });

    function handleSubmit(event) {
      event.preventDefault();
      Inertia.post('/login', form);
    }

    return (
        <Auth>
            <InertiaHead title="Login" />
            
            <form onSubmit={handleSubmit} className="row g-3">
                {Object.keys(status).length > 0 &&
                    <div className="col-12">
                        <div className="alert alert-danger mb-0">
                            {Object.keys(status).map((errorGroup, _key) => (
                                status[errorGroup].map((error, key) => (
                                    <span key={key}>{error}</span>
                                ))
                            ))}
                        </div>
                    </div>
                }
                <div className="col-12">
                    <div className="form-floating">
                        <input type="email" className="form-control" id="email" value={form.email} onChange={(event) => setForm((curLogin) => ({ ...curLogin, email: event.target.value }))} autoFocus />
                        <label htmlFor="email">Email</label>
                    </div>
                </div>
                <div className="col-12">
                    <div className="form-floating">
                        <input type="password" className="form-control" id="password" value={form.password} onChange={(event) => setForm((curLogin) => ({ ...curLogin, password: event.target.value }))} autoComplete="current-password" />
                        <label htmlFor="password">Password</label>
                    </div>
                </div>
                <div className="col-12">
                    <div className="form-check">
                        <input
                            className="form-check-input"
                            type="checkbox"
                            value="1"
                            id="remember"
                            name="remember"
                            checked={form.remember}
                            onChange={() => setForm((curLogin) => ({ ...curLogin, remember: curLogin.remember ? null : true }))}
                        />
                        <label className="form-check-label" htmlFor="remember">
                            <span className="fw-bold">Remember me</span>
                        </label>
                    </div>
                </div>
                <div className="col-12 d-flex justify-content-between">
                    <button className="btn btn-primary me-1" type="submit">
                        <AmaranthIcon icon={aiArrowToBracket} /> Login
                    </button>
                    <InertiaLink href="/forgot-password" className="btn btn-link">
                        <AmaranthIcon icon={aiShieldKey} /> Forgot password
                    </InertiaLink>
                </div>
            </form>
        </Auth>
    )
}
